name: Deploy to Kubernetes

on:
    push:
        branches:
            - main


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push Docker Image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: jimitp/spotify:latest

            - name: Set up AWS CLI
              uses: aws-actions/aws-cli-action@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - name: update to kubeconfig
              run: aws eks --region eu-west-1 update-kubeconfig --name spotify-test


            - name: Deploy to EKS
              run: |
                kubectl apply -f deployment.yaml
                kubectl apply -f service.yaml